# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'win.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Weather(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(755, 703)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("border-radius:15px;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #ffd89b, stop:1 #ffd89b);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.lineEdit_city = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_city.setGeometry(QtCore.QRect(100, 100, 551, 51))
        font = QtGui.QFont()
        font.setFamily("Barlow Condensed ExtraLight")
        font.setPointSize(22)
        font.setItalic(True)
        self.lineEdit_city.setFont(font)
        self.lineEdit_city.setStyleSheet("border-radius:12px;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #19547b, stop:1 #19547b);\n"
"color:#ffd89b;")
        self.lineEdit_city.setObjectName("lineEdit_city")
        self.pushButton_exit = QtWidgets.QPushButton(self.frame)
        self.pushButton_exit.setGeometry(QtCore.QRect(380, 169, 271, 51))
        font = QtGui.QFont()
        font.setFamily("Barlow Condensed ExtraLight")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.pushButton_exit.setFont(font)
        self.pushButton_exit.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_exit.setStyleSheet("QPushButton{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #19547b, stop:1 #19547b);\n"
"color:#ffd89b;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #ffd89b, stop:1 #ffd89b);\n"
"color:#19547b\n"
"};")
        self.pushButton_exit.setObjectName("pushButton_exit")
        self.pushButton_done = QtWidgets.QPushButton(self.frame)
        self.pushButton_done.setGeometry(QtCore.QRect(100, 169, 261, 51))
        font = QtGui.QFont()
        font.setFamily("Barlow Condensed ExtraLight")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.pushButton_done.setFont(font)
        self.pushButton_done.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_done.setStyleSheet("QPushButton{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #19547b, stop:1 #19547b);\n"
"color:#ffd89b;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #ffd89b, stop:1 #ffd89b);\n"
"color:#19547b\n"
"};")
        self.pushButton_done.setObjectName("pushButton_done")
        self.label_min_temp = QtWidgets.QLabel(self.frame)
        self.label_min_temp.setGeometry(QtCore.QRect(132, 350, 181, 61))
        font = QtGui.QFont()
        font.setFamily("Barlow Condensed Light")
        font.setPointSize(16)
        font.setItalic(True)
        self.label_min_temp.setFont(font)
        self.label_min_temp.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #ffd89b, stop:1 #ffd89b);\n"
"color:#19547b")
        self.label_min_temp.setObjectName("label_min_temp")
        self.label_pressure = QtWidgets.QLabel(self.frame)
        self.label_pressure.setGeometry(QtCore.QRect(133, 420, 181, 61))
        font = QtGui.QFont()
        font.setFamily("Barlow Condensed Light")
        font.setPointSize(16)
        font.setItalic(True)
        self.label_pressure.setFont(font)
        self.label_pressure.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #ffd89b, stop:1 #ffd89b);\n"
"color:#19547b")
        self.label_pressure.setObjectName("label_pressure")
        self.label_sunset = QtWidgets.QLabel(self.frame)
        self.label_sunset.setGeometry(QtCore.QRect(390, 420, 181, 61))
        font = QtGui.QFont()
        font.setFamily("Barlow Condensed Light")
        font.setPointSize(16)
        font.setItalic(True)
        self.label_sunset.setFont(font)
        self.label_sunset.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #ffd89b, stop:1 #ffd89b);\n"
"color:#19547b")
        self.label_sunset.setObjectName("label_sunset")
        self.label_wind_speed = QtWidgets.QLabel(self.frame)
        self.label_wind_speed.setGeometry(QtCore.QRect(110, 560, 181, 61))
        font = QtGui.QFont()
        font.setFamily("Barlow Condensed Light")
        font.setPointSize(16)
        font.setItalic(True)
        self.label_wind_speed.setFont(font)
        self.label_wind_speed.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #ffd89b, stop:1 #ffd89b);\n"
"color:#19547b")
        self.label_wind_speed.setObjectName("label_wind_speed")
        self.label_max_temp = QtWidgets.QLabel(self.frame)
        self.label_max_temp.setGeometry(QtCore.QRect(379, 350, 181, 61))
        font = QtGui.QFont()
        font.setFamily("Barlow Condensed Light")
        font.setPointSize(16)
        font.setItalic(True)
        self.label_max_temp.setFont(font)
        self.label_max_temp.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #ffd89b, stop:1 #ffd89b);\n"
"color:#19547b")
        self.label_max_temp.setObjectName("label_max_temp")
        self.label_humidity = QtWidgets.QLabel(self.frame)
        self.label_humidity.setGeometry(QtCore.QRect(128, 490, 181, 61))
        font = QtGui.QFont()
        font.setFamily("Barlow Condensed Light")
        font.setPointSize(16)
        font.setItalic(True)
        self.label_humidity.setFont(font)
        self.label_humidity.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #ffd89b, stop:1 #ffd89b);\n"
"color:#19547b")
        self.label_humidity.setObjectName("label_humidity")
        self.label_sunrise = QtWidgets.QLabel(self.frame)
        self.label_sunrise.setGeometry(QtCore.QRect(385, 490, 181, 61))
        font = QtGui.QFont()
        font.setFamily("Barlow Condensed Light")
        font.setPointSize(16)
        font.setItalic(True)
        self.label_sunrise.setFont(font)
        self.label_sunrise.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #ffd89b, stop:1 #ffd89b);\n"
"color:#19547b")
        self.label_sunrise.setObjectName("label_sunrise")
        self.label_condition = QtWidgets.QLabel(self.frame)
        self.label_condition.setGeometry(QtCore.QRect(370, 560, 181, 61))
        font = QtGui.QFont()
        font.setFamily("Barlow Condensed Light")
        font.setPointSize(16)
        font.setItalic(True)
        self.label_condition.setFont(font)
        self.label_condition.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #ffd89b, stop:1 #ffd89b);\n"
"color:#19547b")
        self.label_condition.setObjectName("label_condition")
        self.label_temp_now = QtWidgets.QLabel(self.frame)
        self.label_temp_now.setGeometry(QtCore.QRect(130, 260, 221, 61))
        font = QtGui.QFont()
        font.setFamily("Barlow Condensed Light")
        font.setPointSize(48)
        font.setItalic(True)
        self.label_temp_now.setFont(font)
        self.label_temp_now.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #ffd89b, stop:1 #ffd89b);\n"
"color:#19547b")
        self.label_temp_now.setObjectName("label_temp_now")
        self.label_city = QtWidgets.QLabel(self.frame)
        self.label_city.setGeometry(QtCore.QRect(380, 260, 221, 61))
        font = QtGui.QFont()
        font.setFamily("Barlow Condensed Light")
        font.setPointSize(48)
        font.setItalic(True)
        self.label_city.setFont(font)
        self.label_city.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #ffd89b, stop:1 #ffd89b);\n"
"color:#19547b")
        self.label_city.setObjectName("label_city")
        self.horizontalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.pushButton_exit.clicked.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lineEdit_city.setPlaceholderText(_translate("MainWindow", "                                Enter your city "))
        self.pushButton_exit.setText(_translate("MainWindow", "Exit"))
        self.pushButton_done.setText(_translate("MainWindow", "Done"))
        self.label_min_temp.setText(_translate("MainWindow", "Min temp : "))
        self.label_pressure.setText(_translate("MainWindow", "Pressure : "))
        self.label_sunset.setText(_translate("MainWindow", "Sunset : "))
        self.label_wind_speed.setText(_translate("MainWindow", "Wind speed : "))
        self.label_max_temp.setText(_translate("MainWindow", "Max temp : "))
        self.label_humidity.setText(_translate("MainWindow", "Humidity : "))
        self.label_sunrise.setText(_translate("MainWindow", "Sunrise : "))
        self.label_condition.setText(_translate("MainWindow", "Condition : "))
        self.label_temp_now.setText(_translate("MainWindow", "0c"))
        self.label_city.setText(_translate("MainWindow", "City"))


